
service: serverless-dynamodb-streams-example 

plugins:
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline

custom:
  env: ${file(config/${opt:stage}-env.json)}
  dynamodb:
    stages:
      - ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment: ${self:custom.env}

functions:
  createTask:
    handler: handler.createTask
    
package:
  individually: true
  exclude:
    - dev-env.json
    - prod-env.json
    - node_modules/aws-sdk/**