
service: serverless-dynamodb-streams-example 

custom: ${file(config/${opt:stage}-env.json)}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment: ${self:custom}

functions:
  handler:
    handler: handler.handler
    
package:
  individually: true
  exclude:
    - dev-env.json
    - prod-env.json
    - node_modules/aws-sdk/**